### ISSUE TITLE
Seems to be no top level identifiers for the json objects

### ISSUE THREAD

**Issue by zmaril** [influence-usa/lobbying_federal_domestic#21]
I was under the assumption that the json itself would have a key corresponding to some sort of ocd object.

**Comment by boblannon** [comment]
so the JSON you received from me is really just a convenience object, containing the objects that you'll want to ingest (`disclosure`, `registrant`, `client`, an array of `lobbyists`, etc.)  i could have sent them as separate files, but it seemed like too much overhead.
